### PR TITLE
Capture YieldExpressions

### PR DESCRIPTION
**Pull request by jamestalmage**
This updates code instrumentation to capture YieldExpressions

### CODE REVIEW

**Comment by twada** [comment]
@jamestalmage Thank you for your great contribution!
It looks good to me.
I'll cut a new release as 1.1.0 soon.

**Comment by jamestalmage** [comment]
Cool!

Be sure to ping me when the release is cut so I can update https://github.com/power-assert-js/power-assert-formatter/pull/19

**Comment by twada** [comment]
@jamestalmage Of course! :smiley:

**Comment by twada** [comment]
@jamestalmage [Just released 1.1.0](https://github.com/power-assert-js/espower/blob/master/CHANGELOG.md#110-2015-11-03). Thanks a lot!

**Pull request merged**
